name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # 明确指定 Node.js 版本，避免文件读取问题
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.1'
    
    # 使用最直接的方式安装 pnpm
    - name: Install pnpm
      run: |
        npm install -g pnpm@9
        echo "PNPM version: $(pnpm --version)"
    
    # 安装依赖
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    # 运行各个步骤
    - name: Run lint
      run: pnpm lint
    
    - name: Run test
      run: pnpm test --if-present
    
    - name: Run build
      run: pnpm build